# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default 
  adapter: postgresql
  host: localhost
  port: 5432
  database: accounts
  user: jimmyfigueroa
  password: postgres
  schema_search_path: "dev"

development:
  adapter: postgresql
  host: localhost
  port: 5432
  database: accounts
  user: jimmyfigueroa
  password: postgres
  schema_search_path: "dev"

test:
  adapter: postgresql
  host: localhost
  port: 5432
  database: accounts
  user: jimmyfigueroa
  password: postgres
  schema_search_path: "test"

production:
  adapter: postgresql
  host: localhost
  port: 5432
  database: accounts
  user: jimmyfigueroa
  password: postgres
  schema_search_path: "production"

